name: Sync Frontend Branches with Main
on:
  push:
    branches:
      - main
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This explicitly grants write permission to the workflow
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history
        token: ${{ github.token }}  # Use the built-in token
    
    - name: Set up Git config
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Sync basic branch
      run: |
        git fetch origin
        git checkout -B basic main
        
        # Delete excluded frontend files for basic tier
        git rm -rf --ignore-unmatch \
         src/components/receptionist/AvailableBeds.tsx \
         src/components/receptionist/Emergency.tsx \
         src/components/pharmacist \
         src/components/laboratorian \
         src/components/admin/BedCreate.tsx \
         src/components/admin/ManageBeds.tsx \
         src/components/admin/ManagePharmacist.tsx \
         src/components/admin/ManageLaboratorian.tsx \
         src/components/admin/PharmacistCreate.tsx \
         src/components/admin/LaboratorianCreate.tsx \
         src/pages/PharmacistDashboard.tsx \
         src/pages/LaboratorianDashboard.tsx \
         src/redux/Action/pharmacistaction.ts \
         src/redux/Action/laboratorianaction.ts \
         src/redux/slice/pharmacistSlice.ts \
         src/redux/slice/laboratorianSlice.ts
        
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/components/Modal.tsx
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/pages/ReceptionistDashboard.tsx
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/redux/Action/adminaction.ts
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/redux/Action/receptionistaction.ts
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/components/admin/wrapper/Createwrapper.tsx
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/components/admin/wrapper/Rolewrapper.tsx
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/components/admin/Reports.tsx
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/redux/store.ts
        sed -i '/^\/\/ *pro *$/,/^\/\/ *end *$/d' src/App.tsx
        sed -i '/^{\/\* *pro *\*\/}$/,/^{\/\* *end *\*\/}$/d' src/App.tsx
        git commit -am "Update basic frontend branch from main" || echo "No changes to commit"
        git push -f origin basic
    
    - name: Sync pro branch
      run: |
        git fetch origin
        git checkout -B pro main
        
        # Delete excluded frontend files for pro tier
        git rm -rf --ignore-unmatch \
          src/components/receptionist/Emergency.tsx \
          src/components/laboratorian \
          src/components/admin/ManageLaboratorian.tsx \
          src/components/admin/LaboratorianCreate.tsx \
          src/pages/LaboratorianDashboard.tsx \
          src/redux/Action/laboratorianaction.ts \
          src/redux/slice/laboratorianSlice.ts

        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/components/Modal.tsx
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/pages/ReceptionistDashboard.tsx
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/redux/Action/adminaction.ts
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/redux/Action/receptionistaction.ts
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/components/admin/wrapper/Createwrapper.tsx
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/components/admin/wrapper/Rolewrapper.tsx
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/components/admin/Reports.tsx
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/redux/store.ts
        sed -i '/^\/\/ *plus *$/,/^\/\/ *end *$/d' src/App.tsx
        sed -i '/^{\/\* *plus *\*\/}$/,/^{\/\* *end *\*\/}$/d' src/App.tsx

        git commit -am "Update pro frontend branch from main" || echo "No changes to commit"
        git push -f origin pro
    
    - name: Sync plus branch
      run: |
        git fetch origin
        git checkout -B plus main
        # Plus gets everything from main, no files to exclude
        git commit -m "Update plus frontend branch from main" || echo "No changes to commit"
        git push -f origin plus